USE [master]
GO

/****** Object:  Database [MediaBase]    Script Date: 9/6/2025 8:17:51 AM ******/
DROP DATABASE [MediaBase]
GO

/****** Object:  Database [MediaBase]    Script Date: 9/6/2025 8:17:51 AM ******/
CREATE DATABASE [MediaBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MediaBase2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\MediaBase2.mdf' , SIZE = 16384KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB )
 LOG ON 
( NAME = N'MediaBase2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\MediaBase2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 8192KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MediaBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MediaBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MediaBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MediaBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MediaBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MediaBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [MediaBase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MediaBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MediaBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MediaBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MediaBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MediaBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MediaBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MediaBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MediaBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MediaBase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MediaBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MediaBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MediaBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MediaBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MediaBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MediaBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MediaBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MediaBase] SET RECOVERY FULL 
GO

ALTER DATABASE [MediaBase] SET  MULTI_USER 
GO

ALTER DATABASE [MediaBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MediaBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MediaBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MediaBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MediaBase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MediaBase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MediaBase] SET QUERY_STORE = ON
GO

ALTER DATABASE [MediaBase] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [MediaBase] SET  READ_WRITE 
GO

